language: rust
addons:
  apt:
    sources:
      - sourceline: 'ppa:libccd-debs/ppa'
      - sourceline: 'ppa:fcl-debs/ppa'
    packages:
      - libccd2
      - libccd-dev
      - libfcl0
      - libfcl-dev
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
